export const resourceLabels: Record<string, string> = {
    "login_event": "from special login event",
    "fortune_strip": "from fortune strip",
    "anni": "from weekly annihilation",
    "new_anni": "from new annihilation",
    "store": "from store",
    "event_stages": "from event stages",
    "login": "from daily login",
    "daily_missions": "from daily missions",
    "weekly_missions": "from weekly missions",
    "monthly_card": "from monthly card",
    "free_monthly_card": "from free monthly card",
    "event_shop": "from event shop",
    "pulls": "from pulls",
    "intel": "from intelligence certificate store",
}